### ISSUE TITLE
I'll fix the broken ones for free.

### ISSUE THREAD

**Issue by nate-games** [Deus-Scissuras/Unblocked-Games-Links#23]
I'm going to send a pull request.

**Comment by Deus-Scissuras** [comment]
You realise I can’t cause when I made it It wasn’t made for other school district and  a lot weren’t broken or blocked

**Comment by nate-games** [comment]
> You realise I can’t cause when I made it It wasn’t made for other school district and a lot weren’t broken or blocked

I don't code on my school chromebook, the broken ones are the ones that simply don't work.

**Comment by Deus-Scissuras** [comment]
other school distract dont have block the same links or break links Im not taliking about ChromeBooks
