### ISSUE TITLE
Oh wait you already fixed it 

### ISSUE THREAD

**Issue by Tacogamerman** [Deus-Scissuras/Unblocked-Games-Links#26]
Nvm lol

**Comment by Deus-Scissuras** [comment]
how did i fix it? I forgot

**Comment by Deus-Scissuras** [comment]
i have my admins On payroll (data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAH0AAAB9CAMAAAC4XpwXAAAAclBMVEUAAAD5+/gAAQD6/Pnw8u/2+PXz9fL9//zt7+yjpaJtb2zq7Onn6eZVV1Xk5uP///4QEhDX2daytLGIiod7fXrNz8zFx8S/wb5ERkNcXlve4N2qrKlzdXIqLClhY2BQUk84OjcaHBmTlZIxMzAjJSKbnZpVVKbLAAAKrUlEQVRoge1aa5ejIAytAr5rAUWtb239/39xAz6qVdvanT37ZbJ7ZhxquSRAchM46SCn/yb/G/3/YX8m+r06r6VK/j0yra5hwH3XxQtxXTdlbRiGeVn9C+vpTVNX12srUtciGGtoFPNy0QxsWf0wfD+1QzmKHH5UP4ZOm/oKHWYMY4sAljaIKbKMZ8L10zTmnEcsdT2whAc/LBHAKJTUf2kQ2jR3Su/XNvKwQQgxUiE0ZGhmlIdBG7uWm9pBENhRJEQsPBhfGmd2Zke+BcLzq5L6G2i5DQGewr86KduMRXbQZTFGoDzCxNCInAlT2eLic5u7lmWA5iCxbxgGIv0sGbE0Rnilx+Hl/xMFOTXX6zmMLQvAAdOEbtUkyEeAx2AbQ7MMQ64DA2nqw+ENBC2YpG1ybCaenFATgm2hZ2L5LLWGni2WEqT5cQzWdw2LyLYeVRvGoA2LFVZE0hwCH/HV76KDlUcQdkUXBrFrQL/YEHkuiNcldX0L7Yz5qT9AaobPPKI9RI60PX+u/0J3/dScIzCqRLe7LjbU/JvMtmMDZ20bBC208ox7AzwREXPREl/zwoPTP6GD6X1tnHUyqQh9ytUHTbDSDBGnaAJD2pMg08p11ddxeKrQic/8aUq1x4NCg1Ux0xbNPx6a0uDg6uvBJ3SRCfNZqU1BfhSnq0YjOn+H7sjdTjSyBbUhRNhBtB4T+gJersBKGKupfIVueL7yzsvhIo3fj8OfaOAeAd8VMz6w70dwueF/CL04rPtJT/hPYMt173yBXqYbqn+6BOfopHsFs70haen/DLqG7BceT98mubQSJnqWr9Av2Tv0NTwtnMxeSibw2puNoffyEHP5EuL76PoOOuCvGq7cf3IBCMKs9Ps4bnvpus4GRjQfAPLzw7pvCb22sTGPJhADLUyIG4e3ho5yr4JMLHarKF+gf5hgqJdqqdmIbbqxbXd25xR01gU83asMzwKSGe/a/oDu6nUnGsyKWBbUkonO9Jjkls1N5O0y74Po4P9jU0Y9k52npVFU5+utf7wXPT905ivkwm8/hU7PWSqdSEv1ISe9ZSJluepDrxNdcZMWz5W39ljOx/M+faE5tx6S6KeBj91a227rYWw9TMIWm4PwnVBzWHdAC4DOmXFyeuTjEvTRi15lT54hTbaVX6PrtLk3A73d/EodSLZFRLhIaqduirJlxpNXRNFz7tm//Iwu6WzQtUFY7wxWosvtjAiO1jn1rQx5aqx4CUKrWDOgP897c+Ui9bwoL8trlYxSJZBoqe/Quu2dCcKh+sK9qs5lLw73XEzW/FZD4inMb+suXXzOhYUt3wOiKISIlLCsgq2tEq4JvQ+ejRMxzwfxfE/mN5usBLnOBDub1Y1VR+/nMEplcmhAUibzWchoRVg3A3ozobeyg7sjfAsbRp9EbSD3Moa6BdzWmqf6zcnDjHNmaH0aSyLpyodw3ITugJ4VEj0J2PvQa8b3pe6j/Tc2nE7pDSY7wEZvNy+49ZtKpbmVGMwZ13L/3wL2QufR9Gk5pYmzvbm73yGZTyJLGZnETvOIxvqtGxa1RD/RWy6N9A5da+me5XdCPD1zH5J40+oSOr150ouQ9QlOLP03rZOkzN6Sf9Tt6r6jvt5UQUSQy2eqA/q9zJRJkKjUGCGo51s0cBP9tJr3XV9Pi2tnoThPqD57sym50h3hdnivcfxXRlfSbThbfSYbFLNJAs+IE0r1aYUAujPQbZOPS/EFuqHcLjLa4+iw9zo7KB4vyqdiREd+WPTmqzNvx/TIiiPpmL1ww7yTPXV9i17r9AbSnKbhybbEHtcYMdSmU0nnzq4z2bWC182o3pzbhR1WC0BXRazTNEbZdmaznF71qp+KPZeDrC6Q6JDPvQ7kG9F28wtX9qDMyA1PfaklWLF95XvB5kyhv8tlV+j6Y1LmknBvimM9XZdvOAsyJZMK5MWxJakAfHA5jP5YZ0sGcKplOXfAz5K+kYbz4JbaETZNVlZdvxrBRJvsZuV63qJLM5ehLSxVlwoHnWo+o/BeUNzC2HVZHGSWckzRvITx6E9f9z3Xc2QBT28096K0hUixGLl6mT6WIoohKDU1x9hisSWzvUVGMfOuS323Xe7KInIvFLezU4b5oFNhk0d4RyKBGEVLAZmW60bC0LxgZdOv0Kev6g9tijKMIMPzxLAVwbE1kF3RXHgW5omDcbagqF+jzzzjJE2QGsqdcW6NadZZju1mM2yIIMNp+USQ9e3NvxPsHt5m5nWGhwYcTb+wDdcabR9LCg3E3jdd5q83+3obv9R9KfOx6mE6K4+P644EStuEE1nTtZ9zg79BlxlHc0sUSW4CvFVLhSxT9kRDmJPLp1WzbfTVqGlThS2TxyBOlu4U9pgKahXQDhPSuM+Stfc5nXyD3h0uWOparovX2CrcII2pqQfOZQWfYX+gu3rrRJM8DAM7dYHIm080foh1yMzkWnM8k9WfgX+IPtkxCYIw6CJGLjD3htYXrRBRJSzUJxCVd4k281GdrhpfowPJr9fjoMW5G6pqHaQgUjK7a9tOFcer1NiuVm6gv5z3W8CzLHScFwePTZ0AwZZJ1yiVL55HvCuvdKdlLI/HCOZ56ThOtZEdjL3Mns6sff74O3Sg15E8HiYyucSiLcv6VV9FJT8+x9XHJ0Mv0SG5C1TWoLJVgrEfycNQx1mPonHygPtRdaIBv39+LrWLrrZ5U9mzIwt4Utk1seIAxjAXm0Eqj4idhOJVjXqFseOAlVWAMjhs4Ven6jVZ3hbQFPEDYsdYvrnfNnXdRR8crH7dPiFbFdNHj4Okq/lL9IkP0B79fb4+igl57mcebIDZC/yy+d4nUYRsnX1uo38aYWZZ8vYnp6YIJX9I27a11THx2zFcPkTfYg8r9FqhR9KhhanlpeLNmSHEt8/R95UfWitZN0BExKlrGIawO/t12QCJ24tFt0R4YfqhtVQbTp03y33mu5LJEWQQvI0uefzni25OGtcfQPLc+eZsqmUxT0NYEsp99M/lte4w8ferLFD1twKmMexXrCTDOKT6Nv7QVpTlueSp6wvBPjijVqXcH0KX9yEixjJAT7M2yMb6yf6uQ7KMfYDU7c67YnNNyDBW9x1ImmVRn0N4LN0zPTpw/r3k7I/WBfrgZR/6ojRK987q0YElv4E+/6NH36i9m3umRwb/hKNP+E+Ai3qGqhrER06CkRceQZ8Qd/6g9/5CBCLK47xz8p8z+Tncju4ywlex7JZAFgF2nR/AIHM9lIu4f5oh7Ov+WAOQw7QSEftpCrQy6JjVI5sm46uA0+/2o+g7Y5EP96RV5kaahTkkMtyXN83cOI7ssrWe0WG3b0fMb4YhC8RFbpGeW4GLx5ba6MjPbB6tnR/h7+qTR9CVt0tCezwImbgF0YihLW5d9SKd/E/B9wSgaYprtHcFYtnmfnHZ5SW6uvp4P/NV2rwhZvTFRZ/X+DL3lPDMxdZrx4PIVkX+L+GVO6S109qcvbwMpSryP4r/8D30fkuceOvIdcC+MHnZ44fRHwNo6tuZS5e3UZbXEOuuO4nBDwyiD0fNtbO5mGdQ6vIt8UWcH77Ydlyaorhd7SzLOFO3vP2Iw7Od15R+d5/0O9GvYQCSFw/QH/MzX4zmP2L/yq/8yq/8yq/8yq/8yq/8yr+QP7VMq6n2sLbcAAAAAElFTkSuQmCC)
