### ISSUE TITLE
Hey Deus

### ISSUE THREAD

**Issue by CoolCodingTeen231** [Deus-Scissuras/Unblocked-Games-Links#27]

**Comment by Deus-Scissuras** [comment]
Wsp Mc Pro x?

**Comment by CoolCodingTeen231** [comment]
I'm good 👍

**Comment by CoolCodingTeen231** [comment]
Anyway how about I help you with your project goggle

**Comment by Deus-Scissuras** [comment]
It was never real

**Comment by CoolCodingTeen231** [comment]
Oh

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras what's up

**Comment by Deus-Scissuras** [comment]
I’m good

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras cool anyway im making JS engine but a newer version

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras ok nvm imma make my own programming language

**Comment by Deus-Scissuras** [comment]
Cool

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras anyway about your  unblocked links

**Comment by CoolCodingTeen231** [comment]
just use a proxy and connect to a different WiFi network and u got unblocked games

**Comment by Deus-Scissuras** [comment]
Dude I know this Now i choose not to

**Comment by Deus-Scissuras** [comment]
And theres no other Good Wifi around with No password Also I cant BruteForce while at school

**Comment by Deus-Scissuras** [comment]
Cause I dont and cant get Python Installed

**Comment by CoolCodingTeen231** [comment]
🤣🤣🤣

**Comment by CoolCodingTeen231** [comment]
U cant get Python installed but why

**Comment by Deus-Scissuras** [comment]
Also I have Administrator On my School Computer

**Comment by CoolCodingTeen231** [comment]
at this point

**Comment by Deus-Scissuras** [comment]
I do

**Comment by Deus-Scissuras** [comment]
It wont boot Up

**Comment by CoolCodingTeen231** [comment]
....

**Comment by Deus-Scissuras** [comment]
I also tried going tho Cmd

**Comment by CoolCodingTeen231** [comment]
and what happened next

**Comment by Deus-Scissuras** [comment]
It just put me back to the installer Page and i cant get passed there

**Comment by CoolCodingTeen231** [comment]
i got an idea

**Comment by Deus-Scissuras** [comment]
give me 20 minutes

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras ok + i think i need to transfer my Python file to you

**Comment by Deus-Scissuras** [comment]
nevermid

**Comment by Deus-Scissuras** [comment]
Sure I guess

**Comment by CoolCodingTeen231** [comment]
hmmm

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras

**Comment by CoolCodingTeen231** [comment]
ju

**Comment by CoolCodingTeen231** [comment]
just download a programming language then do ur Brute Force

**Comment by CoolCodingTeen231** [comment]
Also I dont support you in hacking bt

**Comment by Deus-Scissuras** [comment]
What?

**Comment by CoolCodingTeen231** [comment]
Read above

**Comment by Deus-Scissuras** [comment]
I got a

**Comment by CoolCodingTeen231** [comment]
Cool

**Comment by CoolCodingTeen231** [comment]
Anyway i coded a bot

**Comment by CoolCodingTeen231** [comment]
That likes comments in Github issues

**Comment by CoolCodingTeen231** [comment]
and what happened to it

**Comment by Deus-Scissuras** [comment]
I still have it Im trying to figure out what i can do with it

**Comment by CoolCodingTeen231** [comment]
well i know what u can do with it

**Comment by Deus-Scissuras** [comment]
I can get a fresh Windows Install and extentions

**Comment by Deus-Scissuras** [comment]
I know Im Trying

**Comment by Deus-Scissuras** [comment]
Like Dox All my teachers and stuff

**Comment by Deus-Scissuras** [comment]
Thats realy Bad Tho

**Comment by CoolCodingTeen231** [comment]
like shutting down the wifi

**Comment by Deus-Scissuras** [comment]
I could do that without admin

**Comment by Deus-Scissuras** [comment]
just send Alot of packets it would take 5 mins to crash the servers

**Comment by CoolCodingTeen231** [comment]
type: 
shutdown -i

**Comment by CoolCodingTeen231** [comment]
and arp -d

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras now try those out

**Comment by Deus-Scissuras** [comment]
What IP? It dont show a Ip

**Comment by CoolCodingTeen231** [comment]
...

**Comment by CoolCodingTeen231** [comment]
did u type:
arp -a

**Comment by Deus-Scissuras** [comment]
Yes

**Comment by CoolCodingTeen231** [comment]
It should show Internet Address

**Comment by CoolCodingTeen231** [comment]
can u show me what it looks like

**Comment by Deus-Scissuras** [comment]
I just Typed The Shutdown -l command

**Comment by Deus-Scissuras** [comment]
It logged me out

**Comment by Deus-Scissuras** [comment]
also im not loggeed into admin right now

**Comment by CoolCodingTeen231** [comment]
so u can shutdown pcs?

**Comment by Deus-Scissuras** [comment]
Do you want me to?

**Comment by Deus-Scissuras** [comment]
I could i need the laptops name

**Comment by CoolCodingTeen231** [comment]
You can probably cause April Fools Hack in 2023

**Comment by CoolCodingTeen231** [comment]
and students be like: what

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras just tell the Principal to do it then

**Comment by Deus-Scissuras** [comment]
Tell the Principal What?

**Comment by CoolCodingTeen231** [comment]
To turn there Bluetooth

**Comment by CoolCodingTeen231** [comment]
so they can have a girl

**Comment by Deus-Scissuras** [comment]
Someone slow Had it on

**Comment by Deus-Scissuras** [comment]
Im trying

**Comment by Deus-Scissuras** [comment]
I wonder whos laptop it was

**Comment by CoolCodingTeen231** [comment]
oh

**Comment by CoolCodingTeen231** [comment]
And I think my wifi I am on has alot of people on it

**Comment by Deus-Scissuras** [comment]
OMfgaV Xn xdcn cdnmcd ,.c d

**Comment by CoolCodingTeen231** [comment]
what is that

**Comment by Deus-Scissuras** [comment]
OG G FNFBG  nO` COEEJHDJD

**Comment by Deus-Scissuras** [comment]
HELP EME

**Comment by CoolCodingTeen231** [comment]
what happened

**Comment by Deus-Scissuras** [comment]
you could find the computer name and ping it with cmd to find the account

**Comment by CoolCodingTeen231** [comment]
wow

**Comment by Deus-Scissuras** [comment]
it was The HEadMAster i gotta go

**Comment by CoolCodingTeen231** [comment]
ok

**Comment by CoolCodingTeen231** [comment]
WTF JUST HAPPENED!!!

**Comment by Deus-Scissuras** [comment]
I just booted the headmaster offline for a whole hour

**Comment by CoolCodingTeen231** [comment]
oh

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras what did he do

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras ya there?

**Comment by Deus-Scissuras** [comment]
They are going tho peoples computers in every grade

**Comment by Deus-Scissuras** [comment]
They are at 7th grade im in 8th grade

**Comment by CoolCodingTeen231** [comment]
ok

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras do u work at the Anonymous

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras ok

**Comment by Deus-Scissuras** [comment]
IM GOONNA GET EXPELLED

**Comment by Deus-Scissuras** [comment]
HOLD UP

**Comment by Deus-Scissuras** [comment]
Cas\use i done bad things on my computer at school

**Comment by CoolCodingTeen231** [comment]
like

**Comment by CoolCodingTeen231** [comment]
hacking what stuff

**Comment by CoolCodingTeen231** [comment]
is it bcuz ur dad works at Anonymous

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras hackign what type of stuff ?

**Comment by Deus-Scissuras** [comment]
Accounts, and also Booting websites like edu sites

**Comment by CoolCodingTeen231** [comment]
oh hell no

**Comment by CoolCodingTeen231** [comment]
@YouTube are u real

**Comment by Deus-Scissuras** [comment]
tHEY ARE CHECKING COMPUTERS THO

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras didnt u use a strong VPN

**Comment by Deus-Scissuras** [comment]
They are checking all computers all grades A vpn will only save my iP IM AT SCHOOL RIGHT NOW

**Comment by Deus-Scissuras** [comment]
we dont bring our computers home

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras use a Virtual Machine + Put it in a secret folder which is locked and needs passcode to enter

**Comment by CoolCodingTeen231** [comment]
and if u learn hacking by NetworkChuck he should have made a video on Virtual Machine by now + If Virtual Machine didnt exist then Linux will not have that many people using it

**Comment by Deus-Scissuras** [comment]
DONE

**Comment by Deus-Scissuras** [comment]
TY TY TY TY TGY

**Comment by CoolCodingTeen231** [comment]
No problem bro

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras so u download a Virtual Machine

**Comment by Deus-Scissuras** [comment]
they checked it IM SAFE I Installed one and i just deleted it TY

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras great

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras no problem dude

**Comment by Deus-Scissuras** [comment]
Check ur chat

**Comment by Deus-Scissuras** [comment]
Motaly chat @CoolCodingTeen231

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras bro

**Comment by CoolCodingTeen231** [comment]
...
