### ISSUE TITLE
I_I

### ISSUE THREAD

**Issue by TrickJoker312** [Deus-Scissuras/Unblocked-Games-Links#28]
well
i'm back.
Many of these unblocked sites are blocked now, since i'm in

HIGH

school.
How's it been?

**Comment by Deus-Scissuras** [comment]
Welcome Back I been Gods I started August 2 it’s been terrible but my site has picked up more traffic

**Comment by Deus-Scissuras** [comment]
Hold up I give you some links right now

**Comment by Deus-Scissuras** [comment]
https://yplaz.onrender.com/

**Comment by Deus-Scissuras** [comment]
You got discord?

**Comment by TrickJoker312** [comment]
not right now.

**Comment by Deus-Scissuras** [comment]
Ok

**Comment by Deus-Scissuras** [comment]
Hop on your account after school and give me ur discord

**Comment by Deus-Scissuras** [comment]
My user is deusommuim

**Comment by Deus-Scissuras** [comment]
Here’s A another one don’t put this one up https://ypxza.onrender.com/

**Comment by TrickJoker312** [comment]
Thanks!

**Comment by Deus-Scissuras** [comment]
Ur welcome

**Comment by Deus-Scissuras** [comment]
School today hasn’t started I’m on the Bus

**Comment by Deus-Scissuras** [comment]
Do you quit?

**Comment by CoolCodingTeen231** [comment]
@Deus-Scissuras lol

**Comment by TrickJoker312** [comment]
> Do you quit?

What do you mean?
You mean the Unblocked Sites repo?

**Comment by Deus-Scissuras** [comment]
Like GitHub in general

**Comment by TrickJoker312** [comment]
No. I'm still on, quite a lot.

**Comment by TrickJoker312** [comment]
A bulk list would be very appreciated, but just a couple is amazing as well!

**Comment by Deus-Scissuras** [comment]
I still have my repo use outred.fun
